#---
#- name: Test Ping Connectivity
#  hosts: linux
#  gather_facts: true

#  tasks:
#    - name: Test Ping
#      ping:

---
- name: Install Programs on Ubuntu
  hosts: linux
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install python with sudo
      apt:
        name:
          - software-properties-common
          - python3

    - name: Install pip
      apt:
        name:
          - python3-pip
        state: present

    - name: Install additional Python packages
      pip:
        name:
          - Flask==3.0.0
          - requests==2.29.0
          - psycopg2-binary
        executable: pip3

    - name: Install figlet
      apt:
        name: figlet
        state: present


