---
- name: Install Flask
  hosts: nodes
  become: yes

  tasks:
    - name: Update apt package cache (for Ubuntu/Debian)
      apt:
        update_cache: yes
        
    - name: Install Python and pip
      apt:
        name: python3
        state: present
        
    - name: Install pip
      apt: 
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present
